sudo: required. 

services:
    - docker

before_install:
    - docker build -t johnmatthewd/client_test -f ./client/Dockerfile.dev ./client
    #- docker build -t johnmatthewd/nginx_test -f ./nginx/Dockerfile.dev ./nginx
    #- docker build -t johnmatthewd/server_test -f ./server/Dockerfile.dev ./server
    #- docker build -t johnmatthewd/worker_test -f ./worker/Dockerfile.dev ./worker

script:
    - docker run -e CI=true johnmatthewd/client_test npm run test
    #- docker run -e CI=true johnmatthewd/nginx_test nginx -t
    #- docker run -e CI=true johnmatthewd/server_test npm run test
    #- docker run -e CI=true johnmatthewd/worker_test npm run test

after_success:
    - docker build -t johnmatthewd/client-p ./client 
    - docker build -t johnmatthewd/nginx-p ./nginx
    - docker build -t johnmatthewd/server-p ./server
    - docker build -t johnmatthewd/worker-p ./worker
    

    #Push the images to docker-hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push johnmatthewd/client-p 
    #- docker push johnmatthewd/nginx-p
    #- docker push johnmatthewd/server-p
    #- docker push johnmatthewd/worker-p
    #step 1 login to docker cli

    #AWS Deployment
deploy: 
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: johnmatthewd_Multi_Container_Docker[FIB]
    env: JohnmatthewdMultiContainerDockerfib-env
    bucket_name: elasticbeanstalk-us-east-2-413646379915
    bucket_path: docker-johnmatthewd_Multi_Container_Docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY